### ISSUE TITLE
Intermittent Crash (Report Included)

### ISSUE THREAD

**Issue by 99Blocks** [NFINIT-Development/nfinit-skyblock#30]
Hi Knox,

Thanks for maintaining the pack :)

I have had two crashes this evening, each happening intermittently
- The first time it was night-time and raining and I was literally just looking into the void.
- The second time I was crafting in a Tinkers Construct Crafting Table.

No additions or edits to the pack/mods list.

Here's the opening of the crash: 

```// Why is it breaking :(

Time: 6/8/18 10:23 PM
Description: Ticking player

java.lang.NullPointerException: Ticking player
	at betterquesting.questing.QuestInstance.GetUserEntry(QuestInstance.java:849)
	at betterquesting.questing.QuestInstance.hasClaimed(QuestInstance.java:429)
	at betterquesting.questing.QuestInstance.canClaim(QuestInstance.java:444)
	at betterquesting.questing.QuestInstance.update(QuestInstance.java:177)
	at betterquesting.handlers.EventHandler.onLivingUpdate(EventHandler.java:137)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_994_EventHandler_onLivingUpdate_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:566)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2086)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)
```
And here's a link for the whole thing in pastebin.

https://pastebin.com/MCvfyfkp

Both crash reports were identical so I only shared the one here.

No rush, not a major issue really. Gives me an excuse to take a break and grab a fresh coffee and the gap between the crashes was something like 4 hours.

**Comment by knoxhack** [comment]
Hopefully fixed in version 1.2.10! Don't forget to update your quests with "/bq_admin default load" to fix this bug while updating.
